### ISSUE TITLE
Document and Blog about CLI

### ISSUE THREAD

**Issue by liamawhite** [tetratelabs/getenvoy.io#102]
### Installation
- [x] Binary via Github
- [x] Homebrew
- [x] Docker (https://github.com/tetratelabs/getenvoy/pull/49)

### Getting Started
- [ ] CLI vs Envoy page
- [x] Envoy Subsection
- [x] CLI Subsection

### Other
- [ ] Sidebar docs
- [ ] Sidebar envs
- [ ] Homepage
- [ ] Blog post
- [ ] [Autogenerate Commandline Docs](https://github.com/spf13/cobra/blob/master/doc/md_docs.md)
- [ ] [Test for deadlinks](https://github.com/wjdp/htmltest/wiki/Using-With-Hugo)

**Comment by lunchboxav** [comment]
The bulk of the changes is here https://github.com/liamawhite/getenvoy.io/commit/b757d3d946ba1d86f61f9bd8c9ea9d299ff35c2a

This is the latest state of the Installation page. I've implemented the same sidebar and added ToC to each page as well

![Screen Shot 2019-10-17 at 5 46 14 PM](https://user-images.githubusercontent.com/1574827/67002439-1a02ce00-f106-11e9-9f16-36d143fb3c54.png)

![Screen Shot 2019-10-17 at 5 46 22 PM](https://user-images.githubusercontent.com/1574827/67002443-1c652800-f106-11e9-90ff-317674e4f61c.png)
