### ISSUE TITLE
Disable automatic copy-pasting on code boxes

### ISSUE THREAD

**Issue by perlun** [tetratelabs/getenvoy.io#104]
**What is incorrect, confusing or missing:** Highlighting text on e.g. https://www.getenvoy.io/platforms/envoy/ubuntu/ copies the text automatically to the clipboard

**Suggested fix:** Change this to be a button next to the text, or disable the feature altogether

----

Background: The way that this has been implemented (in #9) has a few challenges:

- It will overwrite the user's clipboard without asking. This is rather impolite and could potentially lead to data loss (what if the user has some very critical text/password in the clipboard and selects text on this web page by accident?)

- It will _deselect_ the text after copying, which means that if you as a user will press Ctrl-C after selecting (like you normally do when you want to copy-paste text from a web page), this is not even possible. To me, this feels confusing and annoying, since it essentially breaks an existing feature in the web browser.

- The implementation has flaws; if you double click, then  continue selecting, you might end up with parts of the "Copied command to clipboard"  text in your clipboard.

For me personally, this feature does much more harm than good. I would be fine with a button for copying the command to the clipboard (like some web pages do it; can't find any good example of it right now). It can even be overlaid on top of the `<pre>` element if we want to avoid affecting other content on the page.

All things considered, thanks for a great project - I am very thankful for what the work you have done thus far. :+1: :+1: :+1:

**Comment by liamawhite** [comment]
This is good feedback and something we hadn't considered. I'll add it to the prioritised list.

**Comment by perlun** [comment]
Thanks @liamawhite and @lunchboxav, much appreciated! :clap: Thanks for a speedy fix.

One minor usability note: when hovering the "copy to clipboard button", the mouse cursor isn't changed to indicate that this is indeed a clickable button. It would be super-great to get this fixed at the same time.

![image](https://user-images.githubusercontent.com/630613/64013850-6cbe0180-cb29-11e9-8782-338d33cfd64b.png)

**Comment by lunchboxav** [comment]
That's actually a very nice suggestion, thanks @perlun, I'll file an issue for this and tackle it.

**Comment by liamawhite** [comment]
Im on it!
