### ISSUE TITLE
CentOS 7 `GLIBC_2.18' not found

### ISSUE THREAD

**Issue by twandrew** [tetratelabs/getenvoy.io#183]
**Describe the bug**
On CentOS 7 Envoy fails with error:
```
 /usr/local/bin/versions/1.16.4/bin/envoy --help
/usr/local/bin/versions/1.16.4/bin/envoy: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /usr/local/bin/versions/1.16.4/bin/envoy)
```

**To Reproduce**
1. Install func-e on CentOS 7 `curl -L https://getenvoy.io/install.sh | bash -s -- -b /usr/local/bin`
2. Install Envoy:  `/usr/local/bin/func-e --home-dir /usr/local/bin use 1.16.4`
3. See error

**Expected behavior**
Help message to be displayed.

**Screenshots**
```
# more /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
# /usr/local/bin/versions/1.16.4/bin/envoy --help
/usr/local/bin/versions/1.16.4/bin/envoy: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /usr/local/bin/versions/1.16.4/bin/envoy)
````

**Environment (please complete the relevant information):**
 - OS: CentOS Linux release 7.3.1611
 - Envoy Version: 1.16.4

**Additional context**
The removal of the yum repository was unfortunate.  

The removal of the RPM instruction page without forwarding was also unfortunate.  

The lack of explanation for the changes to the installation methods in a place which is easy to find is super unfortunate.

Perhaps someone could clarify if the `rpm.dl.getenvoy.io` yum repository will be supported for a time as a legacy source for CentOS 7?  Instructions for the repository were on the website yesterday but have been removed without explanation.  Perhaps the lack of explanation could be corrected?

**Comment by codefromthecrypt** [comment]
The explanation was that "get envoy" is a canceled project because it violates linux trademarks. We no longer publish packages as they are supposed to be published upstream. Please see this for more. https://github.com/envoyproxy/envoy/pull/17246

I'll update the website itself to say explicitly that getenvoy is canceled, also.

**Comment by twandrew** [comment]
I'm very sorry to hear about the project being cancelled.  

It was a great resource for myself, my co-workers, and (I'm sure) many others!

**Comment by codefromthecrypt** [comment]
Appreciate that the combination of bintray turning down and also the trademark things caused some punches, and on behalf of everyone feel your pain and apologize.

on the bright side, envoy will be having package management and replace what's been going on here.

[func-e](https://func-e.io) replaces the CLI and we'll support that also. It has all the [historical versions](https://archive.tetratelabs.io/envoy/envoy-versions.json) even if upstream takes a while to backfill them in package managers

Hope to see you around!
